repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.7.8'
    hooks:
    - id: flake8
      args: [--max-line-length=88]
      exclude: ./*/migrations/
      language_version: python3
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
    - id: mypy
      args: ["--ignore-missing-imports", "--follow-imports=normal"]
      exclude: ./*/migrations/
