version: '3.8'

services:
  app:
    container_name: dentistry_app
    image: dentistry_app:latest
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
      - 8888:8888
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: dentistry_db
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=dentistry

volumes:
  postgres_data:

