version: '3.8'

services:
  app:
    container_name: dentistry_app_prod
    image: dentistry_app_prod:latest
    build: .
    command: gunicorn dentistry.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: dentistry_db_prod
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=dentistry

volumes:
  postgres_data:
