[tool.poetry]
name = "dentistry"
version = "0.1.0"
description = "This is an API for a project to help dentists manage their clinics."
authors = ["M <m@mathsistor.com>", "Sika <sikabarca@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.0.6"
psycopg2-binary = "^2.8.5"
dj-database-url = "^0.5.0"
pytest-django = "^3.9.0"
django-environ = "^0.4.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
