# Generated by Django 3.0.6 on 2020-05-17 23:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(blank=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('second_last_name', models.CharField(blank=True, max_length=50)),
                ('id_document_number', models.CharField(max_length=25)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(choices=[('MA', 'Married'), ('SI', 'Single'), ('DI', 'Divorced'), ('WI', 'Widowed'), ('DP', 'Domestic partnership'), ('NS', 'Not specified')], default='NS', max_length=2)),
                ('birthdate', models.DateField()),
                ('country_of_residence', models.CharField(choices=[('E', 'Ecuador'), ('A', 'Abroad')], default='E', max_length=1)),
                ('address', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('whatsapp', models.BooleanField(default=False)),
                ('health_insurance_company', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('receive_promos', models.BooleanField(default=True)),
                ('referral_source', models.CharField(choices=[('P', 'Personal reference'), ('S', 'Social media'), ('O', 'Other')], max_length=1)),
                ('emergency_contact', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('representative', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('family_history', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('personal_history', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('general_practitioners', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
