# Generated by Django 3.0.6 on 2020-05-21 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='photo',
            new_name='profile_picture_url',
        ),
    ]
