# Generated by Django 3.0.8 on 2020-08-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_rename_photo_to_profile_picture_url_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='first_appointment_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
