# Generated by Django 3.0.8 on 2020-08-01 04:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_patient_first_appointment_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('family_history', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('personal_history', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('general_practitioners', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('drinker', models.BooleanField(default=False)),
                ('smoker', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical_records.Patient')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
