# Generated by Django 3.0.8 on 2020-08-01 06:33

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0006_nonpathologicalbackground'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('intraoral_exam', models.TextField(blank=True, default='')),
                ('extraoral_exam', models.TextField(blank=True, default='')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical_records.Patient')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
