# Generated by Django 3.0.8 on 2020-08-04 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0007_clinicalexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalbackground',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_background', related_query_name='medical_background', to='medical_records.Patient'),
        ),
    ]
