# Generated by Django 3.0.8 on 2020-08-04 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0009_move_history_from_patient_to_medicalbackground'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='family_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='general_practitioners',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='personal_history',
        ),
    ]
