# Generated by Django 3.0.8 on 2020-08-04 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0010_remove_fields_in_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalbackground',
            name='drinker',
        ),
        migrations.RemoveField(
            model_name='medicalbackground',
            name='smoker',
        ),
    ]
