# Generated by Django 3.1.4 on 2020-12-29 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0011_remove_drinker_smoker_from_medicalbackground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodontalexam',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='periodontal_exam', related_query_name='periodontal_exam', to='medical_records.patient'),
        ),
    ]
