# Generated by Django 3.1.4 on 2020-12-29 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0013_update_related_names_non_pathological_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalexam',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_exam', related_query_name='clinical_exam', to='medical_records.patient'),
        ),
    ]
