# Generated by Django 3.1.4 on 2020-12-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0014_update_related_names_clinical_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalbackground',
            name='family_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalbackground',
            name='general_practitioners',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalbackground',
            name='personal_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='representative',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
