PROVINCES_OF_ECUADOR = [
    {"value": 1, "label": "Azuay"},
    {"value": 2, "label": "Bolívar"},
    {"value": 3, "label": "Carchi"},
    {"value": 4, "label": "Cañar"},
    {"value": 5, "label": "Chimborazo"},
    {"value": 6, "label": "Cotopaxi"},
    {"value": 7, "label": "El Oro"},
    {"value": 8, "label": "Esmeraldas"},
    {"value": 9, "label": "Galápagos"},
    {"value": 10, "label": "Guayas"},
    {"value": 11, "label": "Imbabura"},
    {"value": 12, "label": "Loja"},
    {"value": 13, "label": "Los Ríos"},
    {"value": 14, "label": "Manabí"},
    {"value": 15, "label": "Morona Santiago"},
    {"value": 16, "label": "Napo"},
    {"value": 17, "label": "Orellana"},
    {"value": 18, "label": "Pastaza"},
    {"value": 19, "label": "Pichincha"},
    {"value": 20, "label": "Santa Elena"},
    {"value": 21, "label": "Santo Domingo de los Tsáchilas"},
    {"value": 22, "label": "Sucumbíos"},
    {"value": 23, "label": "Tungurahua"},
    {"value": 24, "label": "Zamora Chinchipe"},
]

CANTONS_OF_ECUADOR = {
    1: [
        {"value": 1, "label": "Camilo Ponce Enríquez"},
        {"value": 2, "label": "Chordeleg"},
        {"value": 3, "label": "Cuenca"},
        {"value": 4, "label": "El Pan"},
        {"value": 5, "label": "Girón"},
        {"value": 6, "label": "Guachapala"},
        {"value": 7, "label": "Gualaceo"},
        {"value": 8, "label": "Nabón"},
        {"value": 9, "label": "Oña"},
        {"value": 10, "label": "Paute"},
        {"value": 11, "label": "Pucará"},
        {"value": 12, "label": "San Fernando"},
        {"value": 13, "label": "Santa Isabel"},
        {"value": 14, "label": "Sevilla de Oro"},
        {"value": 15, "label": "Sigsig"},
    ],
    2: [
        {"value": 16, "label": "Caluma"},
        {"value": 17, "label": "Chillanes"},
        {"value": 18, "label": "Chimbo"},
        {"value": 19, "label": "Echeandía"},
        {"value": 20, "label": "Guaranda"},
        {"value": 21, "label": "Las Naves"},
        {"value": 22, "label": "San Miguel"},
    ],
    3: [
        {"value": 23, "label": "Bolívar"},
        {"value": 24, "label": "Espejo"},
        {"value": 25, "label": "Mira"},
        {"value": 26, "label": "Montúfar"},
        {"value": 27, "label": "San Pedro de Huaca"},
        {"value": 28, "label": "Tulcán"},
    ],
    4: [
        {"value": 29, "label": "Azogues"},
        {"value": 30, "label": "La Troncal"},
        {"value": 31, "label": "Biblián"},
        {"value": 32, "label": "Cañar"},
        {"value": 33, "label": "Déleg"},
        {"value": 34, "label": "El Tambo"},
        {"value": 35, "label": "Suscal"},
    ],
    5: [
        {"value": 36, "label": "Alausí"},
        {"value": 37, "label": "Chambo"},
        {"value": 38, "label": "Chunchi"},
        {"value": 39, "label": "Colta"},
        {"value": 40, "label": "Cumandá"},
        {"value": 41, "label": "Guamote"},
        {"value": 42, "label": "Guano"},
        {"value": 43, "label": "Pallatanga"},
        {"value": 44, "label": "Penipe"},
        {"value": 45, "label": "Riobamba"},
    ],
    6: [
        {"value": 46, "label": "La Maná"},
        {"value": 47, "label": "Latacunga"},
        {"value": 48, "label": "Pangua"},
        {"value": 49, "label": "Pujilí"},
        {"value": 50, "label": "Salcedo"},
        {"value": 51, "label": "Saquisilí"},
        {"value": 52, "label": "Sigchos"},
    ],
    7: [
        {"value": 53, "label": "Arenillas"},
        {"value": 54, "label": "Atahualpa"},
        {"value": 55, "label": "Balsas"},
        {"value": 56, "label": "Chilla"},
        {"value": 57, "label": "El Guabo"},
        {"value": 58, "label": "Huaquillas"},
        {"value": 59, "label": "Las Lajas"},
        {"value": 60, "label": "Machala"},
        {"value": 61, "label": "Marcabelí"},
        {"value": 62, "label": "Pasaje"},
        {"value": 63, "label": "Piñas"},
        {"value": 64, "label": "Portovelo"},
        {"value": 65, "label": "Santa Rosa"},
        {"value": 66, "label": "Zaruma"},
    ],
    8: [
        {"value": 67, "label": "Atacames"},
        {"value": 68, "label": "Eloy Alfaro"},
        {"value": 69, "label": "Esmeraldas"},
        {"value": 70, "label": "Muisne"},
        {"value": 71, "label": "Quinindé"},
        {"value": 72, "label": "Río Verde"},
        {"value": 73, "label": "San Lorenzo"},
    ],
    9: [
        {"value": 74, "label": "Isabela"},
        {"value": 75, "label": "San Cristóbal"},
        {"value": 76, "label": "Santa Cruz"},
    ],
    10: [
        {"value": 77, "label": "Alfredo Baquerizo Moreno (Jujan)"},
        {"value": 78, "label": "Balao"},
        {"value": 79, "label": "Balzar (San Jacinto de Balzar)"},
        {"value": 80, "label": "Colimes"},
        {"value": 81, "label": "Coronel Marcelino Maridueña"},
        {"value": 82, "label": "Daule"},
        {"value": 83, "label": "Durán"},
        {"value": 84, "label": "El Empalme"},
        {"value": 85, "label": "El Triunfo"},
        {"value": 86, "label": "General Antonio Elizalde (Bucay)"},
        {"value": 87, "label": "Guayaquil"},
        {"value": 88, "label": "Isidro Ayora"},
        {"value": 89, "label": "Lomas de Sargentillo"},
        {"value": 90, "label": "Milagro"},
        {"value": 91, "label": "Naranjal"},
        {"value": 92, "label": "Naranjito"},
        {"value": 93, "label": "Nobol"},
        {"value": 94, "label": "Palestina"},
        {"value": 95, "label": "Pedro Carbo"},
        {"value": 96, "label": "Playas (General Villamil Playas)"},
        {"value": 97, "label": "Salitre (Urbina Jado)"},
        {"value": 98, "label": "Samborondón"},
        {"value": 99, "label": "Santa Lucía"},
        {"value": 100, "label": "Simón Bolívar"},
        {"value": 101, "label": "Yaguachi"},
    ],
    11: [
        {"value": 102, "label": "Antonio Ante"},
        {"value": 103, "label": "Cotacachi"},
        {"value": 104, "label": "Ibarra"},
        {"value": 105, "label": "Otavalo"},
        {"value": 106, "label": "Pimampiro"},
        {"value": 107, "label": "San Miguel de Urcuquí"},
    ],
    12: [
        {"value": 108, "label": "Calvas"},
        {"value": 109, "label": "Catamayo"},
        {"value": 110, "label": "Celica"},
        {"value": 111, "label": "Chaguarpamba"},
        {"value": 112, "label": "Espíndola"},
        {"value": 113, "label": "Gonzanamá"},
        {"value": 114, "label": "Loja"},
        {"value": 115, "label": "Macará"},
        {"value": 116, "label": "Olmedo"},
        {"value": 117, "label": "Paltas"},
        {"value": 118, "label": "Pindal"},
        {"value": 119, "label": "Puyango"},
        {"value": 120, "label": "Quilanga"},
        {"value": 121, "label": "Saraguro"},
        {"value": 122, "label": "Sozoranga"},
        {"value": 123, "label": "Zapotillo"},
    ],
    13: [
        {"value": 124, "label": "Baba"},
        {"value": 125, "label": "Babahoyo"},
        {"value": 126, "label": "Buena Fé"},
        {"value": 127, "label": "Mocache"},
        {"value": 128, "label": "Montalvo"},
        {"value": 129, "label": "Palenque"},
        {"value": 130, "label": "Pueblo Viejo"},
        {"value": 131, "label": "Quevedo"},
        {"value": 132, "label": "Quinsaloma"},
        {"value": 133, "label": "Urdaneta"},
        {"value": 134, "label": "Valencia"},
        {"value": 135, "label": "Ventanas"},
        {"value": 136, "label": "Vinces"},
    ],
    14: [
        {"value": 137, "label": "Bolívar"},
        {"value": 138, "label": "Chone"},
        {"value": 139, "label": "El Carmen"},
        {"value": 140, "label": "Flavio Alfaro"},
        {"value": 141, "label": "Jama"},
        {"value": 142, "label": "Jaramijó"},
        {"value": 143, "label": "Jipijapa"},
        {"value": 144, "label": "Junín"},
        {"value": 145, "label": "Manta"},
        {"value": 146, "label": "Montecristi"},
        {"value": 147, "label": "Olmedo"},
        {"value": 148, "label": "Paján"},
        {"value": 149, "label": "Pedernales"},
        {"value": 150, "label": "Pichincha"},
        {"value": 151, "label": "Portoviejo"},
        {"value": 152, "label": "Puerto López"},
        {"value": 153, "label": "Rocafuerte"},
        {"value": 154, "label": "San Vicente"},
        {"value": 155, "label": "Santa Ana"},
        {"value": 156, "label": "Sucre"},
        {"value": 157, "label": "Tosagua"},
        {"value": 158, "label": "Veinticuatro de Mayo"},
    ],
    15: [
        {"value": 159, "label": "Gualaquiza"},
        {"value": 160, "label": "Huamboya"},
        {"value": 161, "label": "Limón Indanza"},
        {"value": 162, "label": "Logroño"},
        {"value": 163, "label": "Morona"},
        {"value": 164, "label": "Pablo Sexto"},
        {"value": 165, "label": "Palora"},
        {"value": 166, "label": "San Juan Bosco"},
        {"value": 167, "label": "Santiago de Méndez (Santiago)"},
        {"value": 168, "label": "Sucúa"},
        {"value": 169, "label": "Taisha"},
        {"value": 170, "label": "Tiwintza"},
    ],
    16: [
        {"value": 171, "label": "Archidona"},
        {"value": 172, "label": "Carlos Julio Arosemena Tola"},
        {"value": 173, "label": "El Chaco"},
        {"value": 174, "label": "Quijos"},
        {"value": 175, "label": "Tena"},
    ],
    17: [
        {"value": 176, "label": "Aguarico"},
        {"value": 177, "label": "Francisco de Orellana"},
        {"value": 178, "label": "Joya de los Sachas"},
        {"value": 179, "label": "Loreto"},
    ],
    18: [
        {"value": 180, "label": "Arajuno"},
        {"value": 181, "label": "Mera"},
        {"value": 182, "label": "Pastaza"},
        {"value": 183, "label": "Santa Clara"},
    ],
    19: [
        {"value": 184, "label": "Cayambe"},
        {"value": 185, "label": "Mejía"},
        {"value": 186, "label": "Pedro Moncayo"},
        {"value": 187, "label": "Pedro Vicente Maldonado"},
        {"value": 188, "label": "Puerto Quito"},
        {"value": 189, "label": "Quito"},
        {"value": 190, "label": "Rumiñahui"},
        {"value": 191, "label": "San Miguel de Los Bancos"},
    ],
    20: [
        {"value": 192, "label": "La Libertad"},
        {"value": 193, "label": "Salinas"},
        {"value": 194, "label": "Santa Elena"},
    ],
    21: [
        {"value": 195, "label": "Santo Domingo de los Colorados (Santo Domingo)"},
        {"value": 196, "label": "La Concordia"},
    ],
    22: [
        {"value": 197, "label": "Cascales"},
        {"value": 198, "label": "Cuyabeno"},
        {"value": 199, "label": "Gonzalo Pizarro"},
        {"value": 200, "label": "Lago Agrio"},
        {"value": 201, "label": "Putumayo"},
        {"value": 202, "label": "Shushufindi"},
        {"value": 203, "label": "Sucumbíos"},
    ],
    23: [
        {"value": 204, "label": "Ambato"},
        {"value": 205, "label": "Baños"},
        {"value": 206, "label": "Cevallos"},
        {"value": 207, "label": "Mocha"},
        {"value": 208, "label": "Patate"},
        {"value": 209, "label": "Pelileo"},
        {"value": 210, "label": "Píllaro"},
        {"value": 211, "label": "Quero"},
        {"value": 212, "label": "Tisaleo"},
    ],
    24: [
        {"value": 213, "label": "Centinela del Cóndor"},
        {"value": 214, "label": "Chinchipe"},
        {"value": 215, "label": "El Pangui"},
        {"value": 216, "label": "Nangaritza"},
        {"value": 217, "label": "Palanda"},
        {"value": 218, "label": "Paquisha"},
        {"value": 219, "label": "Yacuambi"},
        {"value": 220, "label": "Yantzaza"},
        {"value": 221, "label": "Zamora"},
    ],
}

DISEASES = [
    {"value": 1, "label": "Diabetes"},
    {"value": 2, "label": "Hypertension"},
    {"value": 3, "label": "Cardiovascular disease"},
    {"value": 4, "label": "Neoplasm"},
    {"value": 5, "label": "Epilepsy"},
    {"value": 6, "label": "Malformation"},
    {"value": 7, "label": "AIDS"},
    {"value": 8, "label": "Kidney diseases"},
    {"value": 9, "label": "Hepatitis"},
    {"value": 10, "label": "Arthritis"},
    {"value": 11, "label": "Others"},
    {"value": 12, "label": "Drinker"},
    {"value": 13, "label": "Smoker"},
]
