PROVINCES_OF_ECUADOR = [
    {"key": 1, "name": "Azuay"},
    {"key": 2, "name": "Bolívar"},
    {"key": 3, "name": "Carchi"},
    {"key": 4, "name": "Cañar"},
    {"key": 5, "name": "Chimborazo"},
    {"key": 6, "name": "Cotopaxi"},
    {"key": 7, "name": "El Oro"},
    {"key": 8, "name": "Esmeraldas"},
    {"key": 9, "name": "Galápagos"},
    {"key": 10, "name": "Guayas"},
    {"key": 11, "name": "Imbabura"},
    {"key": 12, "name": "Loja"},
    {"key": 13, "name": "Los Ríos"},
    {"key": 14, "name": "Manabí"},
    {"key": 15, "name": "Morona Santiago"},
    {"key": 16, "name": "Napo"},
    {"key": 17, "name": "Orellana"},
    {"key": 18, "name": "Pastaza"},
    {"key": 19, "name": "Pichincha"},
    {"key": 20, "name": "Santa Elena"},
    {"key": 21, "name": "Santo Domingo de los Tsáchilas"},
    {"key": 22, "name": "Sucumbíos"},
    {"key": 23, "name": "Tungurahua"},
    {"key": 24, "name": "Zamora Chinchipe"},
]
